version: '3.8'

services:
  user-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: user-db
    environment:
      SA_PASSWORD: "SAadmin!123"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - userdb_data:/var/opt/mssql

volumes:
  userdb_data:
